repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

  - repo: local
    hooks:

    - id: clj-lint
      name: Linter for Clojure
      entry: clj-kondo --lint
      language: system
      files: (\.clj)$

    - id: clj-style
      name: Check Clojure code style
      entry: cljstyle
      language: system
      args: ["check"]
      files: (\.clj)$
