version: "3.9"
name: wishlist

services:

  api:
    container_name: api
    image: docker.io/clojure
    working_dir: /api
    environment:
      DEBUG: "true"
    ports:
      - 3000:3000
    command: [ "lein", "run" ]
    volumes:
      - ./:/api
      - maven-deps:/root/.m2
    restart: unless-stopped

volumes:
  maven-deps:
    name: maven-deps
