name: QA workflow

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
    paths:
      - '**.clj'
      - src/**
      - test/**

jobs:

  static-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          clj-kondo: 2023.02.17
          cljstyle: 0.15.0
          
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Static analyze
        run: clj-kondo --lint src test

      - name: Check code style
        if: ${{ always() }}
        run: cljstyle check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: 2.10.0
          
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Run tests
        run: lein test
